name: Perfect iOS IPA
on: [push]
jobs:
  ipa:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Node 22 No Cache
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'  # 캐시 새로
          
      - name: NPM INSTALL ONLY (no ci!)
        run: |
          npm --version
          npm install --legacy-peer-deps --no-audit --verbose
          
      - name: Capacitor Setup
        run
